/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ServiceIdRouteImport } from './routes/$serviceId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as ToolsToolIdRouteImport } from './routes/tools.$toolId'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppPricingRouteImport } from './routes/app.pricing'
import { Route as AppNicheFinderRouteImport } from './routes/app.niche-finder'
import { Route as AppForensicsRouteImport } from './routes/app.forensics'
import { Route as AppFlaggedRouteImport } from './routes/app.flagged'
import { Route as AppDailyReportRouteImport } from './routes/app.daily-report'
import { Route as AppAppealsRouteImport } from './routes/app.appeals'
import { Route as AppChannelsIndexRouteImport } from './routes/app.channels.index'
import { Route as AppChannelsIdRouteImport } from './routes/app.channels.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceIdRoute = ServiceIdRouteImport.update({
  id: '/$serviceId',
  path: '/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ToolsToolIdRoute = ToolsToolIdRouteImport.update({
  id: '/tools/$toolId',
  path: '/tools/$toolId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPricingRoute = AppPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AppRoute,
} as any)
const AppNicheFinderRoute = AppNicheFinderRouteImport.update({
  id: '/niche-finder',
  path: '/niche-finder',
  getParentRoute: () => AppRoute,
} as any)
const AppForensicsRoute = AppForensicsRouteImport.update({
  id: '/forensics',
  path: '/forensics',
  getParentRoute: () => AppRoute,
} as any)
const AppFlaggedRoute = AppFlaggedRouteImport.update({
  id: '/flagged',
  path: '/flagged',
  getParentRoute: () => AppRoute,
} as any)
const AppDailyReportRoute = AppDailyReportRouteImport.update({
  id: '/daily-report',
  path: '/daily-report',
  getParentRoute: () => AppRoute,
} as any)
const AppAppealsRoute = AppAppealsRouteImport.update({
  id: '/appeals',
  path: '/appeals',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsIndexRoute = AppChannelsIndexRouteImport.update({
  id: '/channels/',
  path: '/channels/',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsIdRoute = AppChannelsIdRouteImport.update({
  id: '/channels/$id',
  path: '/channels/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$serviceId': typeof ServiceIdRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/appeals': typeof AppAppealsRoute
  '/app/daily-report': typeof AppDailyReportRoute
  '/app/flagged': typeof AppFlaggedRoute
  '/app/forensics': typeof AppForensicsRoute
  '/app/niche-finder': typeof AppNicheFinderRoute
  '/app/pricing': typeof AppPricingRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/tools/$toolId': typeof ToolsToolIdRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/app/channels/$id': typeof AppChannelsIdRoute
  '/app/channels/': typeof AppChannelsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$serviceId': typeof ServiceIdRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/appeals': typeof AppAppealsRoute
  '/app/daily-report': typeof AppDailyReportRoute
  '/app/flagged': typeof AppFlaggedRoute
  '/app/forensics': typeof AppForensicsRoute
  '/app/niche-finder': typeof AppNicheFinderRoute
  '/app/pricing': typeof AppPricingRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/tools/$toolId': typeof ToolsToolIdRoute
  '/app': typeof AppIndexRoute
  '/blog': typeof BlogIndexRoute
  '/app/channels/$id': typeof AppChannelsIdRoute
  '/app/channels': typeof AppChannelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$serviceId': typeof ServiceIdRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/appeals': typeof AppAppealsRoute
  '/app/daily-report': typeof AppDailyReportRoute
  '/app/flagged': typeof AppFlaggedRoute
  '/app/forensics': typeof AppForensicsRoute
  '/app/niche-finder': typeof AppNicheFinderRoute
  '/app/pricing': typeof AppPricingRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/tools/$toolId': typeof ToolsToolIdRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/app/channels/$id': typeof AppChannelsIdRoute
  '/app/channels/': typeof AppChannelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$serviceId'
    | '/admin'
    | '/app'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/sitemap.xml'
    | '/app/appeals'
    | '/app/daily-report'
    | '/app/flagged'
    | '/app/forensics'
    | '/app/niche-finder'
    | '/app/pricing'
    | '/app/reports'
    | '/app/settings'
    | '/auth/callback'
    | '/blog/$slug'
    | '/tools/$toolId'
    | '/app/'
    | '/blog/'
    | '/app/channels/$id'
    | '/app/channels/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$serviceId'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/sitemap.xml'
    | '/app/appeals'
    | '/app/daily-report'
    | '/app/flagged'
    | '/app/forensics'
    | '/app/niche-finder'
    | '/app/pricing'
    | '/app/reports'
    | '/app/settings'
    | '/auth/callback'
    | '/blog/$slug'
    | '/tools/$toolId'
    | '/app'
    | '/blog'
    | '/app/channels/$id'
    | '/app/channels'
  id:
    | '__root__'
    | '/'
    | '/$serviceId'
    | '/admin'
    | '/app'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/sitemap.xml'
    | '/app/appeals'
    | '/app/daily-report'
    | '/app/flagged'
    | '/app/forensics'
    | '/app/niche-finder'
    | '/app/pricing'
    | '/app/reports'
    | '/app/settings'
    | '/auth/callback'
    | '/blog/$slug'
    | '/tools/$toolId'
    | '/app/'
    | '/blog/'
    | '/app/channels/$id'
    | '/app/channels/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServiceIdRoute: typeof ServiceIdRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ToolsToolIdRoute: typeof ToolsToolIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$serviceId': {
      id: '/$serviceId'
      path: '/$serviceId'
      fullPath: '/$serviceId'
      preLoaderRoute: typeof ServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/tools/$toolId': {
      id: '/tools/$toolId'
      path: '/tools/$toolId'
      fullPath: '/tools/$toolId'
      preLoaderRoute: typeof ToolsToolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pricing': {
      id: '/app/pricing'
      path: '/pricing'
      fullPath: '/app/pricing'
      preLoaderRoute: typeof AppPricingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/niche-finder': {
      id: '/app/niche-finder'
      path: '/niche-finder'
      fullPath: '/app/niche-finder'
      preLoaderRoute: typeof AppNicheFinderRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/forensics': {
      id: '/app/forensics'
      path: '/forensics'
      fullPath: '/app/forensics'
      preLoaderRoute: typeof AppForensicsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/flagged': {
      id: '/app/flagged'
      path: '/flagged'
      fullPath: '/app/flagged'
      preLoaderRoute: typeof AppFlaggedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/daily-report': {
      id: '/app/daily-report'
      path: '/daily-report'
      fullPath: '/app/daily-report'
      preLoaderRoute: typeof AppDailyReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/appeals': {
      id: '/app/appeals'
      path: '/appeals'
      fullPath: '/app/appeals'
      preLoaderRoute: typeof AppAppealsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/channels/': {
      id: '/app/channels/'
      path: '/channels'
      fullPath: '/app/channels/'
      preLoaderRoute: typeof AppChannelsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/channels/$id': {
      id: '/app/channels/$id'
      path: '/channels/$id'
      fullPath: '/app/channels/$id'
      preLoaderRoute: typeof AppChannelsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAppealsRoute: typeof AppAppealsRoute
  AppDailyReportRoute: typeof AppDailyReportRoute
  AppFlaggedRoute: typeof AppFlaggedRoute
  AppForensicsRoute: typeof AppForensicsRoute
  AppNicheFinderRoute: typeof AppNicheFinderRoute
  AppPricingRoute: typeof AppPricingRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppChannelsIdRoute: typeof AppChannelsIdRoute
  AppChannelsIndexRoute: typeof AppChannelsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppealsRoute: AppAppealsRoute,
  AppDailyReportRoute: AppDailyReportRoute,
  AppFlaggedRoute: AppFlaggedRoute,
  AppForensicsRoute: AppForensicsRoute,
  AppNicheFinderRoute: AppNicheFinderRoute,
  AppPricingRoute: AppPricingRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppChannelsIdRoute: AppChannelsIdRoute,
  AppChannelsIndexRoute: AppChannelsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServiceIdRoute: ServiceIdRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BlogSlugRoute: BlogSlugRoute,
  ToolsToolIdRoute: ToolsToolIdRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
