
"""remove_stripe

Revision ID: fb5bd8ba0964
Revises: 77c923187ced
Create Date: 2026-06-08 14:58:16.852447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb5bd8ba0964'
down_revision: Union[str, None] = '77c923187ced'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'stripe_customer_id')
    op.drop_column('organizations', 'stripe_subscription_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('stripe_subscription_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('stripe_customer_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
